### ISSUE TITLE
[New CFP] 4th Workshop on Real-time And intelliGent Edge computing (RAGE 2025)

### ISSUE THREAD

**Issue by dpliatsios** [CallForPaper/callforpaper-requests#5]
### Event Details

- **Event Name**:  4th Workshop on Real-time And intelliGent Edge computing (RAGE 2025)
- **Event Website**:  [https://rage-workshop.github.io/2025/](url)
- **Submission Deadline**: 20 January 2025
- **Event Date**:  6 May 2025
- **Location**: Irvine, CA, USA

The edge computing paradigm is becoming increasingly popular as it facilitates real-time computation, reduces energy consumption and carbon footprint, and fosters security and privacy preservation by processing the data closer to its origin, thereby drastically reducing the amount of data sent to the cloud. On the application side, there is a growing interest in using edge computing as a key pillar to support decentralized artificial intelligence by implementing federated learning and adaptive deep learning inference at the edge. However, many edge applications tightly interact with the surrounding environment and are required to deliver a result (e.g., perform actuation or send a message through a 5G network) within a predefined deadline. Therefore, a key requirement in edge computing is the need to be predictable across the edge-to-cloud continuum while also efficiently utilizing the system resources.

However, meeting the above requirements is non-trivial. Modern edge devices can be very diverse, ranging from hand-held devices to large in-premise servers, and can include complex embedded platforms with multiple heterogeneous cores and hardware accelerators such as GPUs, TPUs, and FPGAs. This complexity introduces considerable challenges when trying to guarantee timing requirements of real-time applications: for example, due to scheduling policies implemented by the hardware accelerators (often not publicly disclosed by vendors) or due to the memory contention experienced by applications when accessing main memory concurrently in a multi-core setup. Secondly, network transmission time (TSN over Ethernet to 5G links) can lead to variability in the end-to-end latencies incurred by edge applications. Thirdly, a distributed infrastructure is naturally exposed to security attacks potentially able to compromise the execution of one or multiple devices or threaten their corresponding communications.

Furthermore, the operating system (OS) also plays a crucial role in enabling the edge computing paradigm, but quite often at the price of increasing the difficulty in deriving timing guarantees: for example, think of a complex deep neural network that needs to leverage a Linux-based OS (which is far more complicated than a real-time operating system), since it provides all the software stacks (e.g., TensorRT) and device drivers to interact with NVIDIA GPUs.

The complexity of the problem is further increased by the usage of middleware frameworks, which simplify the development of applications, but at the cost of introducing scheduling policies in addition to the one offered by the underlying operating system, hindering predictability. Some relevant examples are ROS, in the context of robotics, TensorFlow for artificial intelligence, TensorRT for efficient deep neural network inference on GPUs, and others. Virtualization technologies are also becoming crucial in implementing the edge paradigm, but again, at the expense of creating a more complex operating environment, where guaranteeing temporal properties is a challenging endeavor. These problems are common to many application domains, including cyber-physical systems, future-generation autonomous driving applications, robotics, Industry 4.0, smart buildings, and more.

We solicit the submission of work-in-progress papers. Workshop topics include, but are not limited to:
- Real-time edge computing
- QoS mechanisms for temporal isolation in light-weight virtualization mechanisms (Docker, WebAssembly)
- Mechanisms for end-to-end latency guarantees in the edge-to-cloud continuum
- Methods for functional decomposition between the edge and cloud
- Predictability in middleware frameworks (ROS, TensorFlow, TensorRT, and more)
- Real-time edge computing use cases
- Real-time network protocols for edge computing
- Real-time distributed artificial intelligence
- Resource scheduling and allocation in embedded real-time systems
- Predictable and efficient parallel applications
- Energy- and power-aware allocation in the edge-to-cloud Continuum
- Timing predictability for artificial intelligence
- Security and safety verification techniques for edge computing and infrastructures
- Software/hardware/communication mechanisms, analysis, and/or tools supporting security in edge computing or in critical infrastructures

Organizers
Technical Program Committee Co-Chairs:
- Miguel Gutiérrez Gaitán, Pontificia Universidad Católica de Chile, Chile
- Arpan Gujarati, University of British Columbia, BC, Canada
- Eirini Eleni Tsiropoulou, Arizona State University, USA

Steering Committee:
- Daniel Casini, Scuola Superiore Sant’Anna, Italy
- Dakshina Dasari, Robert Bosch GmbH, Germany
- Matthias Becker, KTH Royal Institute of Technology, Sweden

Publicity Chair: Dimitrios Pliatsios, University of Western Macedonia, Greece

Web Chair: Gabriele Serra, Scuola Superiore Sant’Anna, Italy

Venue
The conference will be held in Irvine, CA, USA, as part of the CPS-IoT-Week 2025. May 6th, 2025.

Contact
All questions about submissions should be emailed to miguel.gutierrez@uc.cl, arpanbg@cs.ubc.ca, eirini@unm.edu

**Comment by saurabhsharma2u** [comment]
CFP Published: https://callforpaper.org/cfp/rage-2025-4th-workshop-on-real-time-and-intelligent-edge-computing_2719
