### ISSUE TITLE
[New CFP] Ninth International Workshop on SCIentific DOCument Analysis (SCIDOCA 2025)

### ISSUE THREAD

**Issue by vtrn988** [CallForPaper/callforpaper-requests#6]
### Event Details

- **Event Name**:  Ninth International Workshop on SCIentific DOCument Analysis (SCIDOCA 2025)
- **Event Website**: https://sites.google.com/view/SCIDOCA/2025/
- **Submission Deadline**: Jan 26, 2025
- **Event Date**: May 27-30, 2025   
- **Location**: [Osaka International Convention Center](https://www.gco.co.jp/), Osaka, Japan and Online

Recent proliferation of scientific papers and technical documents has become an obstacle to efficient information acquisition of new information in various fields. It is almost impossible for individual researchers to check and read all related documents. Even retrieving relevant documents is becoming harder and harder. This workshop gathers all the researchers and experts who are aiming at scientific document analysis from various perspectives, and invite technical paper presentations and system demonstrations that cover any aspects of scientific document analysis.

As a special focus this year, we organize a shared task of Citation Prediction, Discovery, and Placement within scientific documents, which aims at boosting the study of relevancy among scientific documents. More details here:  https://sites.google.com/view/scidoca/2025/shared-task

Publication
Selected papers will be published in the proceedings of JSAI-isAI via Springer Verlag "Lecture Notes in Artificial Intelligence" series. More details: https://www.ai-gakkai.or.jp/isai/

Venue
Osaka International Convention Center, Osaka, Japan and Online

Submission Guidelines
All papers must be original and not simultaneously submitted to another journal or conference. The following paper categories are welcome:

Long paper on original and completed work, including concrete evaluation and analysis wherever appropriate; and
Short paper on a small, focused contribution, work in progress, a negative result, or an opinion piece.

List of Topics
- text analysis
- document structure analysis
- logical structure analysis
- figure and table analysis
- citation analysis of scientific and technical documents
- scientific information assimilation
- summarization and visualization
- knowledge discovery/mining from scientific papers and data
- similar document retrieval
- entity and relation linking between documents and knowledge base
- survey generation
- resources for scientific documents analysis
- document understanding in general
- NLP systems aiming for scientific documents including tagging, parsing, coreference, etc.
- other related topics

Program Committee
- Nguyen Le Minh, Japan Advanced Institute of Science and Technology
- Noriki Nishida, RIKEN Center for Advanced Intelligence Project
- Vu Tran, The Institute of Statistical Mathematics
- Yusuke Miyao, The University of Tokyo
- Yuji Matsumoto, RIKEN Center for Advanced Intelligence Project
- Yoshinobu Kano, Shizuoka University
- Akiko Aizawa, National Institute of Informatics
- Ken Satoh, National Institute of Informatics and Sokendai
- Junichiro Mori, The University of Tokyo
- Kentaro Inui, Tohoku University
- Nguyen Ha Thanh, National Institute of Informatics
- Nguyen Minh Phuong, Japan Advanced Institute of Science and Technology

Organizing committee
- Minh Le Nguyen, Japan Advanced Institute of Science and Technology
- Yuji Matsumoto, RIKEN Center for Advanced Intelligence Project (Advisor)
- Vu Tran, The Institute of Statistical Mathematics

Contact
nguyenml[at]jaist.ac.jp

**Comment by saurabhsharma2u** [comment]
CFP Published: https://callforpaper.org/cfp/scidoca-2025-scidoca-2025-ninth-international-workshop-on-scientific-document-analysis_2756
